
using Microsoft.Win32;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SmoreVision
{
    static class Program
    {
        /// <summary>
        /// 应用程序的主入口点。
        /// </summary>
        [STAThread]
        static void Main()
        {
            bool createNew;
            try
            {
                //using (System.Threading.Mutex m = new System.Threading.Mutex(true, "Global\\" + Application.ProductName, out createNew))
                {
                    Process[] processes = System.Diagnostics.Process.GetProcessesByName(Application.CompanyName);
                    if (processes.Length > 1)
                    {
                        MessageBox.Show("软件已开启!", "提示!!!", MessageBoxButtons.OK, MessageBoxIcon.Information);

                    }
                    else
                    {
                        AutoGenerateDumpWhenCrash();
                        Application.EnableVisualStyles();
                        Application.SetCompatibleTextRenderingDefault(false);
                        //FormWelcom.ShowSplashScreen();
                        //Application.Run(new FormMain());
                        SMFormWelcom.ShowSplashScreen();//带SM_logo

                    }
                }
            }
            catch (System.Exception ex)
            {
                // SMLogWindow.OutLog($"{ex.ToString()}", Color.Green, loglevel: SmoreControlLibrary.SMLog.LogLevel.Error);
                MessageBox.Show(ex.Message);
            }
        }



        public static void AutoGenerateDumpWhenCrash()
        {
            try
            {
                var outputDmpPath = AppDomain.CurrentDomain.BaseDirectory + "Dump";
                if (!Directory.Exists(outputDmpPath))
                {
                    Directory.CreateDirectory(outputDmpPath);
                }

                var fileName = System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName;
                var processName = fileName.Substring(fileName.LastIndexOf('\\') + 1);

                //注册表地址
                string regPath = @"SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\" + processName;
                var reg = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry64);//Registry64防止注册表重定向到wow64

                var subKey = reg.CreateSubKey(regPath);



                subKey.SetValue("DumpCount", 2, RegistryValueKind.DWord);//dump文件个数
                subKey.SetValue("DumpFolder", outputDmpPath, RegistryValueKind.ExpandString);//dump文件目录
                subKey.SetValue("DumpType", 2, RegistryValueKind.DWord);//dump文件类型

            }
            catch (Exception ex)
            {
                //CLoggerTools.Warning2File(CLoggerFileName.strException, "{0},{1},{2}", "UI.Program", ex.Message, ex.StackTrace.Replace("\r\n", ""));
                return;
            }


        }
    }
}
